services:
  - type: web
    name: notes-app-backend
    env: node
    plan: free
    build:
      - cd server && npm install
    start:
      - cd server && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 18.17.1
  - type: web
    name: notes-app-frontend
    env: static
    plan: free
    build:
      - cd client && npm install && npm run build
    staticPublishPath: ./client/dist
databases:
  - name: notes-db
    databaseName: notes_app
    plan: free
    postgresMajorVersion: 14